"""promptry - regression protection for LLM pipelines."""

__version__ = "0.10.0"

from promptry.registry import track, track_context, track_invocation, vote, save_dataset, load_dataset, PromptRegistry
from promptry.prompts import seed_prompt, get_prompt_template, render_prompt
from promptry.feedback import analyze_votes
from promptry.evaluator import suite, check_all
from promptry.assertions import (
    assert_semantic,
    assert_contains,
    assert_not_contains,
    assert_schema,
    assert_llm,
    assert_json_valid,
    assert_matches,
    assert_grounded,
    assert_tool_called,
    assert_tool_sequence,
    assert_no_tool_called,
    assert_conversation_length,
    assert_all_assistant_turns,
    assert_any_assistant_turn,
    assert_conversation_coherent,
    assert_no_repetition,
    clean_json,
    set_judge,
)
from promptry.conversation import Conversation, Turn
from promptry.runner import run_suite
from promptry.drift import DriftMonitor
from promptry.templates import get_templates, run_safety_audit
from promptry.trajectory import (
    Trajectory,
    TrajectoryStep,
    TrajectoryDiff,
    analyze_trajectory,
    diff_trajectories,
    format_trajectory_diff,
    assert_trajectory_max_steps,
    assert_no_redundant_tool_calls,
    assert_tool_input_matches,
    assert_final_answer_present,
)
from promptry.capture import (
    Capture,
    CaptureRecorder,
    ReplayResult,
    get_recorder,
    default_recorder,
    capture_enabled,
    load_captures,
    iter_captures,
    replay_captures,
    redact_sensitive,
)
from promptry.clustering import (
    cluster_failures,
    format_clustering_report,
    ClusteringReport,
    FailureCluster,
)
from promptry.garak import (
    import_report as import_garak_report,
    parse_garak_jsonl,
    GarakEval,
    GarakRun,
)

__all__ = [
    "track",
    "track_context",
    "track_invocation",
    "seed_prompt",
    "get_prompt_template",
    "render_prompt",
    "vote",
    "save_dataset",
    "load_dataset",
    "analyze_votes",
    "PromptRegistry",
    "suite",
    "check_all",
    "assert_semantic",
    "assert_contains",
    "assert_not_contains",
    "assert_schema",
    "assert_llm",
    "assert_json_valid",
    "assert_matches",
    "assert_grounded",
    "assert_tool_called",
    "assert_tool_sequence",
    "assert_no_tool_called",
    "assert_conversation_length",
    "assert_all_assistant_turns",
    "assert_any_assistant_turn",
    "assert_conversation_coherent",
    "assert_no_repetition",
    "Conversation",
    "Turn",
    "clean_json",
    "set_judge",
    "run_suite",
    "DriftMonitor",
    "get_templates",
    "run_safety_audit",
    "Trajectory",
    "TrajectoryStep",
    "TrajectoryDiff",
    "analyze_trajectory",
    "diff_trajectories",
    "format_trajectory_diff",
    "assert_trajectory_max_steps",
    "assert_no_redundant_tool_calls",
    "assert_tool_input_matches",
    "assert_final_answer_present",
    "Capture",
    "CaptureRecorder",
    "ReplayResult",
    "get_recorder",
    "default_recorder",
    "capture_enabled",
    "load_captures",
    "iter_captures",
    "replay_captures",
    "redact_sensitive",
    "cluster_failures",
    "format_clustering_report",
    "ClusteringReport",
    "FailureCluster",
    "import_garak_report",
    "parse_garak_jsonl",
    "GarakEval",
    "GarakRun",
]
